{"name": "test_login[Padro-asdf]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'Padro', password = 'asdf'\n\n    @pytest.mark.login\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        driver = SeleniumWebDriver(implicitly_wait=1, explicitly_wait=1)\n        page = SauceDemoPage(driver)\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name='users', attachment_type=AttachmentType.PNG)\n        driver.close(exit_time=2)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_03_pytest_allure_screenshot.py:28: AssertionError"}, "attachments": [{"name": "users", "source": "2e315e53-abe7-4a6b-949e-5a4071a18b98-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'Padro'"}, {"name": "password", "value": "'asdf'"}], "start": 1707771545351, "stop": 1707771550635, "uuid": "f5a6e341-421b-42b7-945f-3e8ed18a492d", "historyId": "e38fb943a78fb460336606b4687f7e85", "testCaseId": "b8114e60717ba55b71422ad5396fbcd5", "fullName": "reports.test_03_pytest_allure_screenshot#test_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_03_pytest_allure_screenshot"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "51964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_03_pytest_allure_screenshot"}]}